# 0.0.1 The Boston Housing Dataset

In [2]:
from sklearn.datasets import load_boston
import matplotlib.pyplot as plt
import numpy as np

In [3]:
boston = load_boston()
boston['data']

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]])

In [5]:
x_data = boston.data
y_data = boston.target.reshape(boston.target.size,1)

In [10]:
y_data.shape

(506, 1)

In [12]:
from sklearn import preprocessing

In [13]:
minmax_scale = preprocessing.MinMaxScaler(feature_range= (0,5)).fit(x_data)
#standard_scale = preprocessing.StandardScaler().fit(x_data)
x_scaled_data = minmax_scale.transform(x_data)

x_scaled_data[:3]

array([[0.00000000e+00, 9.00000000e-01, 3.39076246e-01, 0.00000000e+00,
        1.57407407e+00, 2.88752635e+00, 3.20803296e+00, 1.34601570e+00,
        0.00000000e+00, 1.04007634e+00, 1.43617021e+00, 5.00000000e+00,
        4.48399558e-01],
       [1.17961270e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 2.73998850e+00, 3.91349125e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 5.00000000e+00,
        1.02235099e+00],
       [1.17848872e-03, 0.00000000e+00, 1.21151026e+00, 0.00000000e+00,
        8.64197531e-01, 3.47192949e+00, 2.99691040e+00, 1.74480990e+00,
        2.17391304e-01, 5.24809160e-01, 2.76595745e+00, 4.94868627e+00,
        3.17328918e-01]])

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled_data, y_data, test_size = 0.33 )


In [15]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((339, 13), (167, 13), (339, 1), (167, 1))

In [16]:
from sklearn import linear_model

regr = linear_model.LinearRegression(fit_intercept = True,
                                    normalize = False,
                                    copy_X = True,
                                    n_jobs = 8)

regr.fit(X_train, y_train)
regr

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=8, normalize=False)

In [17]:
regr.coef_, regr.intercept_

(array([[-0.66679486,  0.71111587,  0.0099389 ,  0.4988735 , -1.49602431,
          4.05106151, -0.23978248, -3.0807434 ,  1.22658797, -1.2849151 ,
         -1.8435618 ,  0.98510527, -3.60344962]]), array([25.69434067]))

In [18]:
# the coefficients

print('Coefficients: ', regr.coef_)
print('intercept: ', regr.intercept_)

Coefficients:  [[-0.66679486  0.71111587  0.0099389   0.4988735  -1.49602431  4.05106151
  -0.23978248 -3.0807434   1.22658797 -1.2849151  -1.8435618   0.98510527
  -3.60344962]]
intercept:  [25.69434067]


In [19]:
regr.predict(x_data[:5])

array([[ 1.83830631],
       [33.57650443],
       [55.34390609],
       [85.81240916],
       [78.00133079]])

In [20]:
x_data[:5].dot(regr.coef_.T) + regr.intercept_

array([[ 1.83830631],
       [33.57650443],
       [55.34390609],
       [85.81240916],
       [78.00133079]])

In [21]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error

In [22]:
y_true = y_test
y_hat = regr.predict(X_test)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat),\
mean_squared_error(y_true, y_hat)

(0.7054569728942913, 3.550303645358026, 27.627094179662965)

In [23]:
y_true = y_train
y_hat = regr.predict(X_train)

r2_score(y_true, y_hat), mean_absolute_error(y_true, y_hat),\
mean_squared_error(y_true, y_hat)

(0.754194990563259, 3.1054392922591343, 19.60865701871145)

In [24]:
regr.score(X_test, y_test)

0.7054569728942913