In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import VotingClassifier

In [2]:
X = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [3]:
X[:5]

array([[0.27345609, 0.01415106, 0.        , 1.        , 0.        ,
        0.125     , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        1.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.473882  , 0.13913574, 0.        , 0.        , 1.        ,
        0.125     , 0.25      , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.32356257, 0.01546857, 0.        , 1.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.    

In [4]:
y[:5]

array([0., 1., 1., 1., 0.])

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3 )

In [6]:
clflog = LogisticRegression(random_state= 1)
clfdt= DecisionTreeClassifier(random_state =1)
clfgn= GaussianNB()
eclf_h = VotingClassifier(estimators= [('lr',clflog),\
                                      ('rf', clfdt),\
                                      ('gnb',clfgn)],\
                                      voting= 'hard')
eclf_s = VotingClassifier(estimators= [('lr',clflog),\
                                      ('rf',clfdt),\
                                      ('gnb',clfgn)],\
                                      voting='soft')

In [7]:
models = [clflog, clfdt, clfgn, eclf_h, eclf_s]

In [8]:
for model in models:
    model.fit(x_train, y_train)
    pred = model.predict(x_test)
    score = model.score(x_test, y_test)
    print(model)
    print(score)
    print('-'*20)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=1, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)
0.8089887640449438
--------------------
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best')
0.7415730337078652
--------------------
GaussianNB(priors=None, var_smoothing=1e-09)
0.7602996254681648
--------------------
VotingClassifier(estimators=[('lr', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [9]:
from sklearn.model_selection import cross_val_score
for model in models:
    scores = cross_val_score(model, x_train, y_train, cv= 5)
    
    
    print(scores)
    print('\n')
    print(scores.mean())
    print('-'*20)

[0.816      0.848      0.856      0.75       0.84552846]


0.8231056910569106
--------------------
[0.76       0.848      0.792      0.72580645 0.78861789]


0.7828848675583531
--------------------
[0.8        0.792      0.808      0.69354839 0.69105691]


0.756921059533176
--------------------
[0.816      0.856      0.872      0.75       0.79674797]


0.8181495934959349
--------------------
[0.832      0.864      0.864      0.75       0.80487805]


0.8229756097560976
--------------------


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

In [10]:
clf1 = LogisticRegression(random_state = 1)
clf2 = DecisionTreeClassifier(random_state = 1)
eclf1 = VotingClassifier(estimators = [('lr',clf1), ('dt',clf2)], voting= 'hard')
eclf2 = VotingClassifier(estimators = [('lr',clf1), ('dt',clf2)], voting = 'soft')

In [11]:
models = [clf1, clf2, eclf1, eclf2]

for model in models:
    scores = cross_val_score(model, x_train, y_train, cv =5)
    
    print(scores)
    print(scores.mean())
    print('-'*20)

[0.816      0.848      0.856      0.75       0.84552846]
0.8231056910569106
--------------------
[0.76       0.848      0.792      0.72580645 0.78861789]
0.7828848675583531
--------------------
[0.8        0.864      0.832      0.79032258 0.83739837]
0.8247441909257802
--------------------
[0.76       0.848      0.792      0.72580645 0.78861789]
0.7828848675583531
--------------------


C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this w

In [42]:
eclf = VotingClassifier(estimators=[('lr', clf1), ('dt', clf2)], voting='hard')

In [58]:
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

params1 ={"lr__solver" : ['liblinear'], "lr__penalty" : ["l2"],\
          "lr__C" : c_params, "dt__criterion" : ["gini", "entropy"],
          "dt__max_depth": [10,8,7,6,5,4,3,2],
          "dt__min_samples_leaf": [1,2,3,4,5,6,7,8,9]}

In [47]:
c_params = [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]
params ={
"lr__solver" : ['liblinear'], "lr__penalty" : ["l2"], \
"lr__C" : c_params, "dt__criterion" : ["gini", "entropy"],
"dt__max_depth" : [10,8,7,6,5,4,3,2],
"dt__min_samples_leaf": [1,2,3,4,5,6,7,8,9]
}


In [59]:
 # cross_validation(cv), grid_search(param_grid), ensemble(estimator) =>

from sklearn.model_selection import GridSearchCV
grid = GridSearchCV(estimator = eclf, param_grid = params, cv =5)
grid = grid.fit(X,y)

In [60]:
grid.best_score_

0.84251968503937

In [61]:
grid.best_params_

{'dt__criterion': 'gini',
 'dt__max_depth': 10,
 'dt__min_samples_leaf': 5,
 'lr__C': 5.0,
 'lr__penalty': 'l2',
 'lr__solver': 'liblinear'}

In [64]:
c_params= [0.1, 5.0, 7.0, 10.0, 15.0, 20.0, 100.0]

params = {'solver' : ['liblinear'], 'penalty' : ["l2"],
         'C' : c_params}
grid = GridSearchCV(clf1, param_grid= params, cv =5)
grid = grid.fit(X,y)

In [65]:
grid.best_score_

0.8267716535433071

In [66]:
grid.best_params_

{'C': 5.0, 'penalty': 'l2', 'solver': 'liblinear'}