In [1]:
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier

In [2]:
x = np.load("./tatanic_x_train.npy")
y = np.load("./tatanic_y_train.npy")

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.3, random_state =101)

In [4]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(622, 27)
(622,)
(267, 27)
(267,)


In [5]:
x_train[0]

array([0.22334962, 0.01517579, 0.        , 1.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [6]:
y_train[:10]

array([0., 1., 1., 1., 0., 0., 1., 1., 0., 1.])

In [7]:
x_test[0]

array([0.30873565, 0.01571255, 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 1.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       1.        , 0.        , 0.        , 1.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        ])

In [8]:
y_test[:10]

array([0., 0., 1., 1., 0., 0., 0., 0., 0., 1.])

In [9]:
clf2 = DecisionTreeClassifier(random_state=1)
eclf = BaggingClassifier(clf2, oob_score= True)

In [10]:
clf2.fit(x_train, y_train)
preds= clf2.predict(x_test)
clf2.score(x_test,y_test)

0.7865168539325843

In [11]:
eclf.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=None, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [12]:
predictions = eclf.predict(x_test)

In [13]:
eclf.score(x_test,y_test)

0.8202247191011236

In [14]:
from sklearn.metrics import confusion_matrix, classification_report

In [15]:
confusion_matrix(y_test, predictions)

array([[145,  18],
       [ 30,  74]], dtype=int64)

In [16]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.83      0.89      0.86       163
         1.0       0.80      0.71      0.76       104

   micro avg       0.82      0.82      0.82       267
   macro avg       0.82      0.80      0.81       267
weighted avg       0.82      0.82      0.82       267



In [17]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf, x, y, cv=5).mean()

C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probabl

0.8110582111343871

In [18]:
params = {'n_estimators': [10,20,30,40,50,55],
         'max_samples' : [0.5,0.6,0.7,0.8,0.9,1]}

In [19]:
from sklearn.model_selection import GridSearchCV

In [20]:
grid = GridSearchCV(estimator= eclf, param_grid = params)
grid= grid.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:615: RuntimeWarning: invalid value encountered in true_divide
  predictions.sum(axis=1)[:, np.newaxis])
C:\Users\user\Anaconda3\lib\site-packages\sklearn\ensemble\bagging.py:610: UserWarning: Some inputs do not have OOB scores. This probably means too few estimators were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
C:\Users\user\Anaconda3\lib\site-p

In [21]:
grid.best_score_

0.815112540192926

In [22]:
grid.best_params_

{'max_samples': 0.6, 'n_estimators': 55}

In [23]:
grid.best_estimator_.oob_score_

0.8086816720257235

In [24]:
grid.best_estimator_

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=1,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=0.6, n_estimators=55, n_jobs=None, oob_score=True,
         random_state=None, verbose=0, warm_start=False)

In [25]:
grid.score(x_test,y_test)

0.846441947565543