In [1]:
import numpy as np

In [2]:
#resampling

elements = ['one', 'two', 'three']
weights = [0.2,0.3,0.5]

from numpy.random import choice
print(choice(elements))
print(choice(elements, size = 10 , replace= True, p =weights))

one
['three' 'three' 'two' 'three' 'three' 'one' 'two' 'one' 'three' 'three']


In [4]:
X = np.load("./tatanic_X_train.npy")
y = np.load("./tatanic_y_train.npy")

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size= 0.3, random_state = 101)

In [6]:
X_train[:2]

array([[0.22334962, 0.01517579, 0.        , 1.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ],
       [0.22334962, 0.04489301, 0.11111111, 0.5       , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        ]])

In [7]:
y_train[:10]

array([0., 1., 1., 1., 0., 0., 1., 1., 0., 1.])

In [8]:
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

In [9]:
eclf = AdaBoostClassifier\
(base_estimator= DecisionTreeClassifier(max_depth =2), n_estimators = 500, learning_rate =0.1)

In [10]:
from sklearn.model_selection import cross_val_score
cross_val_score(eclf,X_train, y_train, cv =5).mean()

0.8006912442396313

In [11]:
from sklearn.tree import DecisionTreeClassifier
DecisionTreeClassifier()

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [12]:
AdaBoostClassifier()

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [13]:
params = {"base_estimator__criterion" : ['gini','entropy'],
         'base_estimator__max_features': [7,8,],
         'base_estimator__max_depth': [1,2,3,4,5],
         'n_estimators': [23,24,25,26,27],
         'learning_rate': [0.4,0.45,0.5,0.55,0.6]}

In [14]:
from sklearn.model_selection import GridSearchCV

In [21]:
grid = GridSearchCV(estimator= eclf, param_grid = params, cv= 5, n_jobs=7)
grid = grid.fit(X_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [22]:
grid.best_score_

0.8167202572347267

In [23]:
grid.best_params_

{'base_estimator__criterion': 'gini',
 'base_estimator__max_depth': 2,
 'base_estimator__max_features': 8,
 'learning_rate': 0.5,
 'n_estimators': 23}

In [24]:
grid.best_estimator_.feature_importances_

array([0.29185521, 0.12812256, 0.04020227, 0.07776818, 0.05427446,
       0.08192817, 0.06791669, 0.00794918, 0.00384363, 0.01429912,
       0.        , 0.0039659 , 0.        , 0.02911921, 0.02457576,
       0.04234727, 0.        , 0.01840541, 0.02575202, 0.        ,
       0.01440318, 0.04032694, 0.0187363 , 0.        , 0.00867973,
       0.00552883, 0.        ])

In [26]:
grid.score(X_train, y_train)

0.8794212218649518

In [28]:
grid.score(X_test, y_test)

0.8052434456928839