In [1]:
import pandas as pd

In [2]:
data_url= "./uva.txt"

df = pd.read_table(data_url)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  This is separate from the ipykernel package so we can avoid doing imports until


In [3]:
df[:5]

who  Newbie   Age  Gender Household Income Sexual Preference  \
0  id74364       0  54.0    Male           $50-74          Gay male   
1  id84505       0  39.0  Female        Over $100      Heterosexual   
2  id84509       1  49.0  Female           $40-49      Heterosexual   
3  id87028       1  22.0  Female           $40-49      Heterosexual   
4  id76087       0  20.0    Male           $30-39          Bisexual   

      Country Education Attainment Major Occupation Marital Status  \
0     Ontario         Some College         Computer          Other   
1      Sweden         Professional            Other          Other   
2  Washington         Some College       Management          Other   
3     Florida         Some College         Computer        Married   
4  New Jersey         Some College        Education         Single   

  Years on Internet  
0            4-6 yr  
1            1-3 yr  
2        Under 6 mo  
3           6-12 mo  
4            1-3 yr

In [4]:
df.shape

(19583, 11)

In [5]:
df.dtypes

who                      object
Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Country                  object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [7]:
df["Marital Status"].unique()

array(['Other', 'Married', 'Single', 'Divorced', 'Widowed', nan,
       'Separated'], dtype=object)

In [8]:
df.pop('who')
df.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Country                  object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [9]:
df.pop('Country')
df.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
Years on Internet        object
dtype: object

In [10]:
df.pop('Years on Internet')
df.dtypes

Newbie                    int64
Age                     float64
Gender                   object
Household Income         object
Sexual Preference        object
Education Attainment     object
Major Occupation         object
Marital Status           object
dtype: object

In [11]:
df['Gender'] = df['Gender'].astype('category')
df.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income          object
Sexual Preference         object
Education Attainment      object
Major Occupation          object
Marital Status            object
dtype: object

In [12]:
for col in df.columns[3:]:
    df[col] = df[col].astype('category')
df.dtypes

Newbie                     int64
Age                      float64
Gender                  category
Household Income        category
Sexual Preference       category
Education Attainment    category
Major Occupation        category
Marital Status          category
dtype: object

In [13]:
df.head()

Newbie   Age  Gender Household Income Sexual Preference  \
0       0  54.0    Male           $50-74          Gay male   
1       0  39.0  Female        Over $100      Heterosexual   
2       1  49.0  Female           $40-49      Heterosexual   
3       1  22.0  Female           $40-49      Heterosexual   
4       0  20.0    Male           $30-39          Bisexual   

  Education Attainment Major Occupation Marital Status  
0         Some College         Computer          Other  
1         Professional            Other          Other  
2         Some College       Management          Other  
3         Some College         Computer        Married  
4         Some College        Education         Single

In [14]:
df_mf = pd.get_dummies(df)
df_mf.head()

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99  ...  \
0                        1                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [15]:
df_mf.shape

(19583, 38)

In [16]:
df_mf.isnull().sum()

Newbie                                 0
Age                                  561
Gender_Female                          0
Gender_Male                            0
Household Income_$10-19                0
Household Income_$20-29                0
Household Income_$30-39                0
Household Income_$40-49                0
Household Income_$50-74                0
Household Income_$75-99                0
Household Income_Over $100             0
Household Income_Under $10             0
Sexual Preference_Bisexual             0
Sexual Preference_Gay male             0
Sexual Preference_Heterosexual         0
Sexual Preference_Lesbian              0
Sexual Preference_Transgender          0
Sexual Preference_na                   0
Education Attainment_College           0
Education Attainment_Doctoral          0
Education Attainment_Grammar           0
Education Attainment_High School       0
Education Attainment_Masters           0
Education Attainment_Other             0
Education Attain

In [21]:
pd.isnull(df_mf['Age']).head()

0    False
1    False
2    False
3    False
4    False
Name: Age, dtype: bool

In [22]:
df_mf[pd.isnull(df_mf['Age'])].head()

Newbie  Age  Gender_Female  Gender_Male  Household Income_$10-19  \
42        0  NaN              1            0                        0   
98        0  NaN              0            1                        0   
160       0  NaN              0            1                        0   
227       1  NaN              1            0                        0   
278       0  NaN              0            1                        0   

     Household Income_$20-29  Household Income_$30-39  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$40-49  Household Income_$50-74  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$75-99  ...  Major Occupation_Education  \
42                         0  ...                           0   
98                         0  ...                           0   
160                        0  ...                           0   
227                        0  ...                           0   
278                        0  ...                           0   

     Major Occupation_Management  Major Occupation_Other  \
42                             0                       0   
98                             1                       0   
160                            0                       0   
227                            0                       1   
278                            0                       0   

     Major Occupation_Professional  Marital Status_Divorced  \
42                               1                        0   
98                               0                        0   
160                              1                        0   
227                              0                        1   
278                              0                        0   

     Marital Status_Married  Marital Status_Other  Marital Status_Separated  \
42                        0                     0                         0   
98                        1                     0                         0   
160                       1                     0                         0   
227                       0                     0                         0   
278                       1                     0                         0   

     Marital Status_Single  Marital Status_Widowed  
42                       1                       0  
98                       0                       0  
160                      0                       0  
227                      0                       0  
278                      0                       0  

[5 rows x 38 columns]

In [23]:
df_mf.loc[pd.isnull(df_mf['Age'])].head()

Newbie  Age  Gender_Female  Gender_Male  Household Income_$10-19  \
42        0  NaN              1            0                        0   
98        0  NaN              0            1                        0   
160       0  NaN              0            1                        0   
227       1  NaN              1            0                        0   
278       0  NaN              0            1                        0   

     Household Income_$20-29  Household Income_$30-39  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$40-49  Household Income_$50-74  \
42                         0                        0   
98                         0                        0   
160                        0                        0   
227                        0                        0   
278                        0                        0   

     Household Income_$75-99  ...  Major Occupation_Education  \
42                         0  ...                           0   
98                         0  ...                           0   
160                        0  ...                           0   
227                        0  ...                           0   
278                        0  ...                           0   

     Major Occupation_Management  Major Occupation_Other  \
42                             0                       0   
98                             1                       0   
160                            0                       0   
227                            0                       1   
278                            0                       0   

     Major Occupation_Professional  Marital Status_Divorced  \
42                               1                        0   
98                               0                        0   
160                              1                        0   
227                              0                        1   
278                              0                        0   

     Marital Status_Married  Marital Status_Other  Marital Status_Separated  \
42                        0                     0                         0   
98                        1                     0                         0   
160                       1                     0                         0   
227                       0                     0                         0   
278                       1                     0                         0   

     Marital Status_Single  Marital Status_Widowed  
42                       1                       0  
98                       0                       0  
160                      0                       0  
227                      0                       0  
278                      0                       0  

[5 rows x 38 columns]

In [24]:
df_mf.loc[pd.isnull(df_mf['Age'])].head().index

Int64Index([42, 98, 160, 227, 278], dtype='int64')

In [26]:
df_mf.loc[pd.isnull(df_mf['Age']),'Age']= df_mf['Age'].mean()

In [27]:
df_mf['Age'][pd.isnull(df_mf['Age'])]

Series([], Name: Age, dtype: float64)

In [28]:
df_mf.head()

Newbie   Age  Gender_Female  Gender_Male  Household Income_$10-19  \
0       0  54.0              0            1                        0   
1       0  39.0              1            0                        0   
2       1  49.0              1            0                        0   
3       1  22.0              1            0                        0   
4       0  20.0              0            1                        0   

   Household Income_$20-29  Household Income_$30-39  Household Income_$40-49  \
0                        0                        0                        0   
1                        0                        0                        0   
2                        0                        0                        1   
3                        0                        0                        1   
4                        0                        1                        0   

   Household Income_$50-74  Household Income_$75-99  ...  \
0                        1                        0  ...   
1                        0                        0  ...   
2                        0                        0  ...   
3                        0                        0  ...   
4                        0                        0  ...   

   Major Occupation_Education  Major Occupation_Management  \
0                           0                            0   
1                           0                            0   
2                           0                            1   
3                           0                            0   
4                           1                            0   

   Major Occupation_Other  Major Occupation_Professional  \
0                       0                              0   
1                       1                              0   
2                       0                              0   
3                       0                              0   
4                       0                              0   

   Marital Status_Divorced  Marital Status_Married  Marital Status_Other  \
0                        0                       0                     1   
1                        0                       0                     1   
2                        0                       0                     1   
3                        0                       1                     0   
4                        0                       0                     0   

   Marital Status_Separated  Marital Status_Single  Marital Status_Widowed  
0                         0                      0                       0  
1                         0                      0                       0  
2                         0                      0                       0  
3                         0                      0                       0  
4                         0                      1                       0  

[5 rows x 38 columns]

In [29]:
df_mf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19583 entries, 0 to 19582
Data columns (total 38 columns):
Newbie                               19583 non-null int64
Age                                  19583 non-null float64
Gender_Female                        19583 non-null uint8
Gender_Male                          19583 non-null uint8
Household Income_$10-19              19583 non-null uint8
Household Income_$20-29              19583 non-null uint8
Household Income_$30-39              19583 non-null uint8
Household Income_$40-49              19583 non-null uint8
Household Income_$50-74              19583 non-null uint8
Household Income_$75-99              19583 non-null uint8
Household Income_Over $100           19583 non-null uint8
Household Income_Under $10           19583 non-null uint8
Sexual Preference_Bisexual           19583 non-null uint8
Sexual Preference_Gay male           19583 non-null uint8
Sexual Preference_Heterosexual       19583 non-null uint8
Sexual Preference_L

In [30]:
df_mf['Age'] = df_mf['Age'].astype('int')
df_mf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19583 entries, 0 to 19582
Data columns (total 38 columns):
Newbie                               19583 non-null int64
Age                                  19583 non-null int32
Gender_Female                        19583 non-null uint8
Gender_Male                          19583 non-null uint8
Household Income_$10-19              19583 non-null uint8
Household Income_$20-29              19583 non-null uint8
Household Income_$30-39              19583 non-null uint8
Household Income_$40-49              19583 non-null uint8
Household Income_$50-74              19583 non-null uint8
Household Income_$75-99              19583 non-null uint8
Household Income_Over $100           19583 non-null uint8
Household Income_Under $10           19583 non-null uint8
Sexual Preference_Bisexual           19583 non-null uint8
Sexual Preference_Gay male           19583 non-null uint8
Sexual Preference_Heterosexual       19583 non-null uint8
Sexual Preference_Les

In [33]:
x = df_mf.iloc[:,1:].as_matrix()
y = df_mf.iloc[:,0].as_matrix().reshape(-1,1)

x.shape, y.shape

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.
C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  


((19583, 37), (19583, 1))

In [34]:
from sklearn import preprocessing

In [36]:
min_max = preprocessing.MinMaxScaler()

x= min_max.fit_transform(x)
x[:5]

C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int32 was converted to float64 by MinMaxScaler.
  warnings.warn(msg, DataConversionWarning)


array([[0.65333333, 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 1.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        ],
       [0.45333333, 1.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 1.        ,
        0.        , 0.        , 0.        , 1.        , 0.        ,
        0.     

In [37]:
y.shape

(19583, 1)

In [40]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size= 0.2, random_state = 77)

In [41]:
x_train.shape , x_test.shape

((15666, 37), (3917, 37))

In [42]:
from sklearn import linear_model, datasets

In [43]:
logreg= linear_model.LogisticRegression(fit_intercept = True)
logreg.fit(x_train, y_train)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\user\Anaconda3\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [44]:
logreg.predict(x_test[:10])

array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [45]:
logreg.predict_proba(x_test[:10])

array([[0.47688499, 0.52311501],
       [0.81460391, 0.18539609],
       [0.72822527, 0.27177473],
       [0.66158574, 0.33841426],
       [0.49893749, 0.50106251],
       [0.81624342, 0.18375658],
       [0.57709355, 0.42290645],
       [0.84735175, 0.15264825],
       [0.48037549, 0.51962451],
       [0.89163716, 0.10836284]])

In [46]:
x_test.shape, y_test.shape

((3917, 37), (3917, 1))

In [47]:
logreg.predict(x_test) == y_test

array([[False,  True,  True, ...,  True, False,  True],
       [False,  True,  True, ...,  True, False,  True],
       [False,  True,  True, ...,  True, False,  True],
       ...,
       [False,  True,  True, ...,  True, False,  True],
       [False,  True,  True, ...,  True, False,  True],
       [ True, False, False, ..., False,  True, False]])

In [48]:
sum((logreg.predict(x_test) == y_test)) /len(y_test)

array([0.26423283, 0.73576717, 0.73576717, ..., 0.73576717, 0.26423283,
       0.73576717])

In [49]:
logreg.predict_proba(x_test[:10])

array([[0.47688499, 0.52311501],
       [0.81460391, 0.18539609],
       [0.72822527, 0.27177473],
       [0.66158574, 0.33841426],
       [0.49893749, 0.50106251],
       [0.81624342, 0.18375658],
       [0.57709355, 0.42290645],
       [0.84735175, 0.15264825],
       [0.48037549, 0.51962451],
       [0.89163716, 0.10836284]])

In [50]:
logreg.decision_function(x_test[:10])

array([ 0.09252599, -1.4802074 , -0.9856369 , -0.67036883,  0.00425004,
       -1.4911007 , -0.3108534 , -1.7139796 ,  0.07853839, -2.10757408])

In [51]:
logreg.predict(x_test[:10])


array([1, 0, 0, 0, 1, 0, 0, 0, 1, 0], dtype=int64)